name: "Lint"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"
      - "master"

jobs:
  gaplint_basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Install dependencies . . ."
        run: sudo pip install git+https://github.com/reiniscirpons/gaplint.git@github-annotations
      - name: "Run gaplint . . ."
        run: bash etc/gaplint-basic.sh

  gaplint_annotations_no_ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Install dependencies . . ."
        run: sudo pip install git+https://github.com/reiniscirpons/gaplint.git@github-annotations
      - name: "Run gaplint . . ."
        run: bash etc/gaplint-annotations-no-ranges.sh

  gaplint_annotations_ranges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Install dependencies . . ."
        run: sudo pip install git+https://github.com/reiniscirpons/gaplint.git@github-annotations
      - name: "Run gaplint . . ."
        run: bash etc/gaplint-annotations-ranges.sh
